baseURL: "https://simoasnaghi.github.io/"
title: Simone Asnaghi
paginate: 5
theme: charlolamode
defaultContentLanguage : en
publishDir: "docs"


languages:
    en:
        languageName : ":us:"
        baseURLlang: "/"
        contentDir: content/en
        profileMode:
            enabled: true
            title: Simone Asnaghi
            description: |
                Hello, I am Simone.  
                I am an electronic engineer. 
                
            imageUrl: "/images/profile.jpg"
            imageTitle: my image
            # imageWidth: 120
            # imageHeight: 120
        menu:
            main:
                - name: About me
                  url: about/
                  weight: 1
                - name: Projects
                  url: projects/
                  weight: 2
                - name: Resumè
                  url: "https://simoasnaghi.github.io/resume"
                  weight: 3
                - name: Privacy Policy
                  url: privacypolicy/
                  weight: 4
    it:
        languageName : ":it:"
        baseURLlang: "/it"
        contentDir: content/it
        profileMode:
            enabled: true
            title: Simone Asnaghi
            description: |
                Ciao, sono Simone.  
                Sono un ingegnere elettronico. 
                
            imageUrl: "/images/profile.jpg"
            imageTitle: my image
            # imageWidth: 120
            # imageHeight: 120
        menu:
            main:
                - name: Su di me
                  url: about/
                  weight: 1
                - name: Progetti
                  url: progetti/
                  weight: 2
                - name: Resumè
                  url: "https://simoasnaghi.github.io/resume"
                  weight: 3
                - name: Privacy Policy
                  url: privacypolicy/
                  weight: 4

   


params:
    author: Simone Asnaghi


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    since : 2020
    
        
    mainSections:
      - articles

    socialIcons:
        - name: github
          url: "https://github.com/simoasnaghi/"
        - name: gitlab
          url: "https://gitlab.com/simoneasnaghi/"
        - name: twitter
          url: "https://twitter.com/SimoAsnaghi/"
        - name: linkedin
          url: "https://www.linkedin.com/in/simone-asnaghi-45844a185/"
        - name: instagram
          url: "https://www.instagram.com/simone_asnaghi/"
        - name: facebook
          url: "https://www.facebook.com/simone.asnaghi/"
        - name: telegram
          url: "https://www.t.me/Simone_Asnaghi/"
        
            
    #change favicon in images folder (icon for web tab)
    assets:
      favicon: "/images/favicon.ico"
      favicon16x16: "/images/favicon-16x16.png"
      favicon32x32: "/images/favicon-32x32.png"
      apple_touch_icon: "/images/apple-touch-icon.png"
      safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true