baseURL = "https://simoasnaghi.github.io/"
title = "Simone Asnaghi"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
publishDir = "public"

[params]
author = "Simone Asnaghi"
license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Simone Asnaghi's personal website"
keywords = "blog,developer,personal"
info = ["Electronics Engineer"]
avatarURL = "images/profile.jpg"
dateFormat = "2/01/2006"
since = 2020
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/simoasnaghi/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-2x fa-gitlab"
weight = 2
url = "https://gitlab.com/simoneasnaghi/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/SimoAsnaghi/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/simone-asnaghi-45844a185/"

[[params.social]]
name = "Instagram"
icon = "fa fa-2x fa-instagram"
weight = 4
url = "https://www.instagram.com/simone_asnaghi/"

[[params.social]]
name = "Facebook"
icon = "fa fa-2x fa-facebook"
weight = 4
url = "https://www.facebook.com/simone.asnaghi/"

[[params.social]]
name = "Telegram"
icon = "fa fa-2x fa-telegram"
weight = 4
url = "https://www.t.me/Simone_Asnaghi/"





[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

#[[languages.en.menu.main]]
#name = "Blog"
#weight = 2
#url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "Resume"
weight = 3
url = "https://simoasnaghi.github.io/resume/"

[[languages.en.menu.main]]
name = "Privacy policy"
weight = 4
url = "privacy-policy/"

[languages.it]
languageName = ":it:"

[[languages.it.menu.main]]
name = "Su di me"
weight = 1
url = "about/"

#[[languages.it.menu.main]]
#name = "Blog"
#weight = 2
#url = "posts/"

[[languages.it.menu.main]]
name = "Progetti"
weight = 2
url = "projects/"

[[languages.it.menu.main]]
name = "Resume"
weight = 3
url = "https://simoasnaghi.github.io/resume/"

[[languages.it.menu.main]]
name = "Privacy policy"
weight = 4
url = "privacy-policy/"
